import JSZip from 'jszip';
import { KitData } from '@/lib/session-store';

export interface ExportSession {
  id: string;
  brand_name: string;
  module: string;
  agent: string;
  duration_seconds: number;
  document: Record<string, { title: string; content: string }>;
  created_at: string;
}

export async function generateExportZip(session: ExportSession, kitData?: KitData): Promise<Blob> {
  const zip = new JSZip();
  const slug = slugify(session.brand_name);
  const folderName = `${slug}-${session.module}`;
  const folder = zip.folder(folderName)!;

  if (kitData) {
    // Rich brand kit export
    folder.file('README.md', buildKitReadme(session, kitData));
    folder.file(`${session.module}.md`, buildKitModuleFile(session, kitData));
    folder.file('_retrieval-rules.md', buildRetrievalRules(session, kitData));
    folder.file('metadata.yaml', buildMetadata(session));
  } else {
    // Legacy section-based export
    folder.file('README.md', buildReadme(session));
    folder.file(`${session.module}.md`, buildModuleFile(session));
    folder.file('metadata.yaml', buildMetadata(session));
  }

  return zip.generateAsync({ type: 'blob' });
}

// ── Kit-based export builders ──────────────────────────────────────────────

function buildKitReadme(session: ExportSession, kit: KitData): string {
  const date = new Date(session.created_at).toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });
  const moduleTitle = getModuleTitle(session.module);
  const mm = String(Math.floor(session.duration_seconds / 60)).padStart(2, '0');
  const ss = String(session.duration_seconds % 60).padStart(2, '0');

  const promptList = kit.usage_prompts.map((p) => `- ${p}`).join('\n');

  return `# ${session.brand_name} — ${moduleTitle} Kit

> ${kit.tagline}

Generated by [Imprint](https://useimprint.com) on ${date}

## What's in this folder

| File | Description |
|------|-------------|
| \`${session.module}.md\` | Full brand kit — paste this into any AI tool |
| \`_retrieval-rules.md\` | Which sections to load for which tasks |
| \`metadata.yaml\` | Session metadata |

## How to use

1. Add \`${session.module}.md\` to your project or AI tool's context
2. Reference in prompts: "Follow the brand guidelines in /brand/"
3. Use the prompts below to get started immediately

## Try these prompts

${promptList}

## Session Info

- **Agent:** ${session.agent}
- **Date:** ${date}
- **Duration:** ${mm}:${ss}
- **Module:** ${moduleTitle}
- **Sections:** ${kit.sections.length}
`;
}

function buildKitModuleFile(session: ExportSession, kit: KitData): string {
  const frontmatter = `---
type: ${session.module}
brand: "${session.brand_name}"
generated: "${session.created_at}"
agent: "${session.agent}"
session_id: "${session.id}"
version: 2
---

`;

  const regularSections = kit.sections.filter((s) => s.id !== 'agent-directives');

  const sectionsMd = regularSections
    .map((s) => `## ${s.title}\n\n${s.content}`)
    .join('\n\n---\n\n');

  let body = `> ${kit.tagline}\n\n---\n\n${sectionsMd}`;

  if (kit.agent_directives) {
    body += `\n\n---\n\n## Agent Directives\n\n> Paste everything above as context. Use the directives below as rules.\n\n\`\`\`\n${kit.agent_directives}\n\`\`\``;
  }

  if (kit.usage_prompts && kit.usage_prompts.length > 0) {
    const promptList = kit.usage_prompts.map((p) => `- ${p}`).join('\n');
    body += `\n\n---\n\n## How to Use This File\n\nDrop this file into Claude, ChatGPT, or your AI coding tool as context. Try these prompts:\n\n${promptList}`;
  }

  return frontmatter + body;
}

function buildRetrievalRules(session: ExportSession, kit: KitData): string {
  const moduleTitle = getModuleTitle(session.module);

  const rulesText = Object.entries(kit.retrieval_rules)
    .map(([context, sectionIds]) => {
      const label = context.replace(/_/g, ' ').replace(/\b\w/g, (c) => c.toUpperCase());
      const sections = sectionIds
        .map((id) => {
          const found = kit.sections.find((s) => s.id === id);
          return `  - \`${id}\`${found ? ` — ${found.title}` : ''}`;
        })
        .join('\n');
      return `### ${label}\n${sections}`;
    })
    .join('\n\n');

  return `# Retrieval Rules — ${session.brand_name} ${moduleTitle}

This file tells AI tools which sections of \`${session.module}.md\` to load for different tasks.

## When to load which sections

${rulesText}

---

*Generated by Imprint on ${new Date(session.created_at).toLocaleDateString()}*
`;
}

// ── Legacy export builders ─────────────────────────────────────────────────

function buildReadme(session: ExportSession): string {
  const date = new Date(session.created_at).toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });
  const moduleTitle = getModuleTitle(session.module);
  const mm = String(Math.floor(session.duration_seconds / 60)).padStart(2, '0');
  const ss = String(session.duration_seconds % 60).padStart(2, '0');

  return `# ${session.brand_name} — ${moduleTitle}

Generated by [Imprint](https://useimprint.com) on ${date}

## What's in this folder

Structured brand files from your ${moduleTitle} session with ${session.agent}. Drop these into your AI coding tool (Claude Code, Cursor, Windsurf, etc.) and your AI will understand your brand.

## How to use

1. Add this folder to your project or AI tool's context
2. Reference in prompts: "Follow the brand guidelines in /brand/"
3. AI will use these as guardrails for all brand-related output

## Session Info

- **Agent:** ${session.agent}
- **Date:** ${date}
- **Duration:** ${mm}:${ss}
- **Module:** ${moduleTitle}
`;
}

const MODULE_TAGLINES: Record<string, string> = {
  positioning: 'Generated by Imprint. Feed this file into any AI agent to align it with your brand positioning.',
  'voice-tone': 'Generated by Imprint. Feed this file into any AI agent to make it talk like your brand.',
  persona: 'Generated by Imprint. Feed this file into any AI agent so it knows exactly who your customer is.',
  'vision-values': 'Generated by Imprint. Feed this file into any AI agent so it understands what your brand stands for.',
};

export function buildModuleFile(session: ExportSession): string {
  const frontmatter = `---
type: ${session.module}
brand: "${session.brand_name}"
generated: "${session.created_at}"
agent: "${session.agent}"
session_id: "${session.id}"
version: 1
---

`;

  const tagline = MODULE_TAGLINES[session.module] ?? 'Generated by Imprint.';

  const regularEntries = Object.entries(session.document).filter(([key]) => key !== 'agent-directives');
  const directivesEntry = session.document['agent-directives'];

  const sections = regularEntries
    .map(([, data]) => `## ${data.title}\n\n${data.content}`)
    .join('\n\n---\n\n');

  let body = `> ${tagline}\n\n---\n\n` + sections;

  if (directivesEntry) {
    body += `\n\n---\n\n## Agent Directives\n\n> Paste everything above as context. Use the directives below as rules.\n\n\`\`\`\n${directivesEntry.content}\n\`\`\``;
  }

  return frontmatter + body;
}

function buildMetadata(session: ExportSession): string {
  return `brand: "${session.brand_name}"
module: "${session.module}"
agent: "${session.agent}"
session_id: "${session.id}"
generated: "${session.created_at}"
duration_seconds: ${session.duration_seconds}
sections_completed: ${Object.keys(session.document).length}
imprint_version: "1.0.0"
`;
}

function getModuleTitle(module: string): string {
  const titles: Record<string, string> = {
    positioning: 'Brand Positioning',
    'voice-tone': 'Voice & Tone',
    persona: 'Brand Persona',
    'vision-values': 'Vision & Values',
  };
  return titles[module] || module;
}

function slugify(text: string): string {
  return text
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/(^-|-$)/g, '');
}

export function downloadZip(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `${filename}.zip`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
