'use client';
import ReactMarkdown from 'react-markdown';
import { ArrowDownTrayIcon, ArrowPathIcon, DocumentIcon, DocumentTextIcon } from '@heroicons/react/24/outline';
import { generateExportZip, downloadZip } from '@/lib/export';
import { useSessionStore, KitData } from '@/lib/session-store';

interface SectionData {
  title: string;
  content: string;
}

interface SessionCompleteProps {
  sections: Record<string, SectionData>;
  isGenerating?: boolean;
  isGeneratingKit?: boolean;
  onNewSession?: () => void;
}

const MODULE_TITLES: Record<string, string> = {
  positioning: 'Brand Positioning',
  'voice-tone': 'Voice & Tone',
  persona: 'Brand Persona',
  'vision-values': 'Vision & Values',
};

function getModuleTitle(module: string): string {
  return MODULE_TITLES[module] ?? module;
}

/** Build markdown preview from the expanded kit data. */
function buildKitMarkdown(kit: KitData): string {
  const regularSections = kit.sections.filter((s) => s.id !== 'agent-directives');

  const sectionsMd = regularSections
    .map((s) => `## ${s.title}\n\n${s.content}`)
    .join('\n\n---\n\n');

  let result = `> ${kit.tagline}\n\n---\n\n${sectionsMd}`;

  if (kit.agent_directives) {
    result += `\n\n---\n\n## Agent Directives\n\n> Paste everything above as context. Use the directives below as rules.\n\n\`\`\`\n${kit.agent_directives}\n\`\`\``;
  }

  if (kit.usage_prompts && kit.usage_prompts.length > 0) {
    const promptList = kit.usage_prompts.map((p) => `- ${p}`).join('\n');
    result += `\n\n---\n\n## How to Use This File\n\nDrop this file into Claude, ChatGPT, or your AI coding tool as context. Try these prompts:\n\n${promptList}`;
  }

  return result;
}

/** Build markdown preview from old captured sections (fallback). */
function buildSectionsMarkdown(
  sections: Record<string, SectionData>,
  moduleKey: string
): string {
  const MODULE_TAGLINES: Record<string, string> = {
    positioning: 'Generated by Imprint. Feed this file into any AI agent to align it with your brand positioning.',
    'voice-tone': 'Generated by Imprint. Feed this file into any AI agent to make it talk like your brand.',
    persona: 'Generated by Imprint. Feed this file into any AI agent so it knows exactly who your customer is.',
    'vision-values': 'Generated by Imprint. Feed this file into any AI agent so it understands what your brand stands for.',
  };
  const tagline = MODULE_TAGLINES[moduleKey] ?? 'Generated by Imprint.';
  const regularEntries = Object.entries(sections).filter(([key]) => key !== 'agent-directives');
  const directivesEntry = sections['agent-directives'];
  const sectionsMd = regularEntries
    .map(([, data]) => `## ${data.title}\n\n${data.content}`)
    .join('\n\n---\n\n');
  let result = `> ${tagline}\n\n---\n\n${sectionsMd}`;
  if (directivesEntry) {
    result += `\n\n---\n\n## Agent Directives\n\n> Paste everything above as context. Use the directives below as rules.\n\n\`\`\`\n${directivesEntry.content}\n\`\`\``;
  }
  return result;
}

const mdComponents = {
  h1: ({ children }: { children?: React.ReactNode }) => (
    <h1 className="font-awesome-serif text-[22px] leading-[28px] tracking-[-0.44px] text-neutral-50 mb-6">
      {children}
    </h1>
  ),
  h2: ({ children }: { children?: React.ReactNode }) => (
    <h2 className="font-awesome-serif text-[17px] leading-[22px] text-neutral-50 mt-8 mb-3 pb-2 border-b border-neutral-800/70">
      {children}
    </h2>
  ),
  h3: ({ children }: { children?: React.ReactNode }) => (
    <h3 className="font-inter text-[14px] font-semibold text-neutral-200 mt-5 mb-2">
      {children}
    </h3>
  ),
  p: ({ children }: { children?: React.ReactNode }) => (
    <p className="font-inter text-[14px] leading-[23px] text-neutral-300 mb-4">
      {children}
    </p>
  ),
  ul: ({ children }: { children?: React.ReactNode }) => (
    <ul className="mb-4 space-y-1.5 pl-4">{children}</ul>
  ),
  ol: ({ children }: { children?: React.ReactNode }) => (
    <ol className="mb-4 space-y-1.5 pl-4 list-decimal">{children}</ol>
  ),
  li: ({ children }: { children?: React.ReactNode }) => (
    <li className="font-inter text-[14px] leading-[22px] text-neutral-300 flex gap-2">
      <span className="mt-[9px] size-[4px] rounded-full bg-neutral-500 shrink-0" />
      <span>{children}</span>
    </li>
  ),
  strong: ({ children }: { children?: React.ReactNode }) => (
    <strong className="font-semibold text-neutral-100">{children}</strong>
  ),
  em: ({ children }: { children?: React.ReactNode }) => (
    <em className="italic text-neutral-300">{children}</em>
  ),
  pre: ({ children }: { children?: React.ReactNode }) => (
    <pre className="font-mono text-[12px] bg-neutral-900 text-neutral-300 px-4 py-3 rounded-lg overflow-x-auto my-4 border border-neutral-800">
      {children}
    </pre>
  ),
  code: ({ children, className }: { children?: React.ReactNode; className?: string }) => {
    // If it's inside a pre (block code), className will be set
    if (className) {
      return <code className="font-mono text-[12px] text-neutral-300">{children}</code>;
    }
    return (
      <code className="font-mono text-[12px] bg-neutral-800 text-brand-accent px-1.5 py-0.5 rounded">
        {children}
      </code>
    );
  },
  hr: () => <hr className="border-neutral-800 my-6" />,
  blockquote: ({ children }: { children?: React.ReactNode }) => (
    <blockquote className="border-l-2 border-brand-accent pl-4 my-4 text-neutral-400 italic">
      {children}
    </blockquote>
  ),
};

export default function SessionComplete({
  sections,
  isGenerating = false,
  isGeneratingKit = false,
  onNewSession,
}: SessionCompleteProps) {
  const { selectedAgent, selectedModules, brandName, elapsedSeconds, sessionId, kitData } =
    useSessionStore();

  const moduleKey = selectedModules[0] || 'positioning';
  const name = brandName || 'My Brand';
  const slug = name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');
  const moduleTitle = getModuleTitle(moduleKey);

  const sectionEntries = Object.entries(sections);
  const hasSections = sectionEntries.length > 0;

  // Determine what to show
  const showKitLoading = isGeneratingKit;
  const showKit = !isGeneratingKit && kitData !== null;
  const showFallback = !isGeneratingKit && !kitData;

  // Subtitle for the header
  const headerSubtitle = showKit
    ? `${kitData!.sections.length} sections · ${kitData!.usage_prompts.length} usage prompts`
    : showKitLoading
    ? 'Building your brand kit…'
    : hasSections
    ? `${sectionEntries.length} section${sectionEntries.length > 1 ? 's' : ''} captured — review and download`
    : 'Session ended — download includes session metadata';

  // Title for header
  const headerTitle = kitData ? `${moduleTitle} Kit` : 'Session Complete';

  // Build the markdown to render
  const previewMarkdown = showKit
    ? buildKitMarkdown(kitData!)
    : showFallback && hasSections
    ? buildSectionsMarkdown(sections, moduleKey)
    : '';

  const handleDownload = async () => {
    const session = {
      id: sessionId || crypto.randomUUID(),
      brand_name: name,
      module: moduleKey,
      agent: selectedAgent,
      duration_seconds: elapsedSeconds,
      document: sections,
      created_at: new Date().toISOString(),
    };
    const blob = await generateExportZip(session, kitData ?? undefined);
    downloadZip(blob, `${slug}-${moduleKey}`);
  };

  return (
    <div className="flex h-full flex-col bg-brand-surface">

      {/* ── Sticky Header ── */}
      <div className="flex items-center gap-8 border-b border-neutral-800 px-8 py-6 shrink-0">
        <div className="flex-1 min-w-0">
          <h2 className="font-awesome-serif text-[24px] tracking-[-0.48px] text-neutral-50">
            {headerTitle}
          </h2>
          <p className="mt-1 font-inter text-[13px] text-[#8E8E93]">
            {headerSubtitle}
          </p>
        </div>

        {/* Download always visible */}
        <button
          onClick={handleDownload}
          className="flex h-8 items-center gap-1.5 justify-center rounded-full bg-neutral-50 px-3 font-inter text-[12px] font-medium text-black shadow-[0px_2px_4px_0px_rgba(0,0,0,0.2)] transition-opacity hover:opacity-90 whitespace-nowrap shrink-0"
        >
          <ArrowDownTrayIcon className="w-3 h-3 stroke-[2.5]" />
          Download
        </button>
      </div>

      {/* ── Scrollable Body ── */}
      <div className="custom-scrollbar flex-1 overflow-y-auto px-8 py-8">

        {/* Loading state — kit is being generated */}
        {showKitLoading && (
          <div className="flex flex-col items-center justify-center h-full gap-4 text-center">
            <div className="flex size-12 items-center justify-center rounded-full border border-neutral-700 bg-neutral-800/60 animate-pulse">
              <DocumentTextIcon className="size-5 text-neutral-400" />
            </div>
            <div className="space-y-1.5">
              <p className="font-inter text-[15px] font-medium text-neutral-200">
                Building your brand kit...
              </p>
              <p className="font-inter text-[13px] leading-[20px] text-neutral-500 max-w-[240px]">
                Pulling everything together from your session.
              </p>
            </div>
          </div>
        )}

        {/* Kit preview — the wow moment */}
        {showKit && (
          <>
            <div className="mb-6 flex items-center gap-2">
              <DocumentIcon className="size-[13px] text-neutral-500 shrink-0" />
              <span className="font-mono text-[11px] text-neutral-500 tracking-wide">
                {slug}-{moduleKey}.md
              </span>
            </div>
            <div className="space-y-0">
              <ReactMarkdown components={mdComponents}>
                {previewMarkdown}
              </ReactMarkdown>
            </div>
          </>
        )}

        {/* Fallback — old section-based view */}
        {showFallback && hasSections && (
          <>
            <div className="mb-6 flex items-center gap-2">
              <DocumentIcon className="size-[13px] text-neutral-500 shrink-0" />
              <span className="font-mono text-[11px] text-neutral-500 tracking-wide">
                {slug}-{moduleKey}.md
              </span>
            </div>
            <div className="space-y-0">
              <ReactMarkdown components={mdComponents}>
                {previewMarkdown}
              </ReactMarkdown>
            </div>
          </>
        )}

        {/* Fallback — early exit, nothing captured */}
        {showFallback && !hasSections && !isGenerating && (
          <div className="flex flex-col items-center justify-center h-full gap-4 text-center">
            <div className="flex size-12 items-center justify-center rounded-full border border-neutral-700 bg-neutral-800/60">
              <DocumentIcon className="size-5 text-neutral-400" />
            </div>
            <div className="space-y-1.5">
              <p className="font-inter text-[15px] font-medium text-neutral-200">
                Session ended early
              </p>
              <p className="font-inter text-[13px] leading-[20px] text-neutral-500 max-w-[240px]">
                Not enough was captured to build a document. Try a longer session next time.
              </p>
            </div>
          </div>
        )}

        {/* Old generating state (Plan A fallback, kept for compatibility) */}
        {showFallback && !hasSections && isGenerating && (
          <div className="flex flex-col items-center justify-center h-full gap-4 text-center">
            <div className="flex size-12 items-center justify-center rounded-full border border-neutral-700 bg-neutral-800/60 animate-pulse">
              <DocumentTextIcon className="size-5 text-neutral-400" />
            </div>
            <div className="space-y-1.5">
              <p className="font-inter text-[15px] font-medium text-neutral-200">
                Building your document…
              </p>
              <p className="font-inter text-[13px] leading-[20px] text-neutral-500 max-w-[240px]">
                Pulling key insights from your conversation.
              </p>
            </div>
          </div>
        )}
      </div>

      {/* ── Footer ── */}
      <div className="border-t border-neutral-800 px-8 py-6 shrink-0">
        <button
          onClick={onNewSession}
          className="flex h-12 w-full items-center justify-center gap-2 rounded-full border border-neutral-600 bg-[rgba(37,37,37,0.8)] font-inter text-[14px] font-medium text-neutral-200 transition-opacity hover:opacity-80"
        >
          <ArrowPathIcon className="w-3.5 h-3.5 stroke-[2]" />
          Start Another Session
        </button>
      </div>
    </div>
  );
}
